### ISSUE TITLE
perllib functions are are retained in pythonizer conversion - however no link/hook to process them or convert them to python import/lib 

### ISSUE THREAD

**Issue by pateshix** [softpano/pythonizer#132]
File "C2s.py", line 15
    if not ((INFILE:=perllib.open_(f"{sys.argv[1:][0]}", 'r'))):
                   ^
SyntaxError: invalid syntax

Instructions are: 

-s -- Attempt to run standard library functions thru pythonizer for use/require - not recommended!
-S -- Turn off -s
-p -- "import perllib" library instead of including functions inline to emulate perl built-in functions (**_default_**)
-P -- Turn off -p

should this be something else for perllib.<functions> as I have many embedded in my .pl code

**Comment by snoopyjc** [comment]
Hi first of all, please mention in your issue that you're using my version of pythonizer, not the softpano version.  

Also, I need to see the source code or at least the line that generated this and I'll fix it.

**Comment by snoopyjc** [comment]
@pateshix If the ^ above is pointing to the :=, then you're not using at least python 3.8, which is the minimum supported version.  Also it looks like you're not using the latest version of pythonizer - it's up to v0.964.

**Comment by pateshix** [comment]
Here is the sdiff of the header with v0.964 and with/without -p option. Which seems to move the perllib import to the first position. Python 3.8.x is the one in use. Also perl5 is in use for legacy flows.

plxcji019> sdiff run_emx_qa.py _perllib_issue/run_emx_qa.py
#!/usr/bin/env python3                                          #!/usr/bin/env python3
# Generated by "pythonizer -p -d 3 run_emx_qa.pl" v0.964 run  | # Generated by "pythonizer -d 3 run_emx_qa.pl" v0.964 run by
# Implied pythonizer options: -m                                # Implied pythonizer options: -m

# April 5, 2019, add option to run EMX only                     # April 5, 2019, add option to run EMX only
import perllib,sys,os,builtins,re                             | import os,builtins,re,perllib,sys
_str = lambda s: '' if s is None else str(s)                    _str = lambda s: '' if s is None else str(s)
from perllib import Die                                         from perllib import Die
perllib.init_package('main')                                    perllib.init_package('main')

####################                                            ####################
#ReadingInput      #                                            #ReadingInput      #
####################                                            ####################

def ReadingInput(*_args):                                       def ReadingInput(*_args):
    global EXTRA_PROC_FILE,GenerateSP,BotMetal,runEMXonly,Out |     global GenerateSP,FREQ,PROC_FILE,MimMetal,runEMXonly,tmp,
    GenerateSP = 0                                                  GenerateSP = 0
    runEMXonly = 0                                                  runEMXonly = 0
    RunSweep = 0                                                    RunSweep = 0
    if not ((INF:=perllib.open_(f"{sys.argv[1:][0]}", 'r'))):       if not ((INF:=perllib.open_(f"{sys.argv[1:][0]}", 'r'))):
        raise Die(f"Can't open {sys.argv[1:][0]}\n")                    raise Die(f"Can't open {sys.argv[1:][0]}\n")

    while (_d:=perllib.readline(INF)):                              while (_d:=perllib.readline(INF)):
        _d=_d.rstrip("\n")                                              _d=_d.rstrip("\n")
        if not re.search(re.compile(r'[a-z]+',re.I),_d):                if not re.search(re.compile(r'[a-z]+',re.I),_d):
            continue                                                        continue

        if re.search(r'^#',_d):                                         if re.search(r'^#',_d):
            continue                                                        continue

        _d = re.sub(r'^\s+',r'',_d,count=1)                             _d = re.sub(r'^\s+',r'',_d,count=1)
        _d = re.sub(r'(\s+)$',r'',_d,count=1)                           _d = re.sub(r'(\s+)$',r'',_d,count=1)
        _d = re.sub(r'\s+',r' ',_d,count=1)                             _d = re.sub(r'\s+',r' ',_d,count=1)
        tmp = perllib.Array(perllib.split(r' ',_str(_d)))               tmp = perllib.Array(perllib.split(r' ',_str(_d)))

**Comment by pateshix** [comment]
Here is the sdiff of the header with v0.964 and with/without -p option. Which seems to move the perllib import to the first position. Python 3.8.x is the one in use. Also perl5 is in use for legacy flows. 

plxcji019> sdiff run_emx_qa.py _perllib_issue/run_emx_qa.py
#!/usr/bin/env python3                                          #!/usr/bin/env python3
# Generated by "pythonizer -p -d 3 run_emx_qa.pl" v0.964 run  | # Generated by "pythonizer -d 3 run_emx_qa.pl" v0.964 run by 
# Implied pythonizer options: -m                                # Implied pythonizer options: -m

# April 5, 2019, add option to run EMX only                     # April 5, 2019, add option to run EMX only
import perllib,sys,os,builtins,re                             | import os,builtins,re,perllib,sys
_str = lambda s: '' if s is None else str(s)                    _str = lambda s: '' if s is None else str(s)
from perllib import Die                                         from perllib import Die
perllib.init_package('main')                                    perllib.init_package('main')

####################                                            ####################
#ReadingInput      #                                            #ReadingInput      #
####################                                            ####################

def ReadingInput(*_args):                                       def ReadingInput(*_args):
    global EXTRA_PROC_FILE,GenerateSP,BotMetal,runEMXonly,Out |     global GenerateSP,FREQ,PROC_FILE,MimMetal,runEMXonly,tmp,
    GenerateSP = 0                                                  GenerateSP = 0
    runEMXonly = 0                                                  runEMXonly = 0
    RunSweep = 0                                                    RunSweep = 0
    if not ((INF:=perllib.open_(f"{sys.argv[1:][0]}", 'r'))):       if not ((INF:=perllib.open_(f"{sys.argv[1:][0]}", 'r'))):
        raise Die(f"Can't open {sys.argv[1:][0]}\n")                    raise Die(f"Can't open {sys.argv[1:][0]}\n")

    while (_d:=perllib.readline(INF)):                              while (_d:=perllib.readline(INF)):
        _d=_d.rstrip("\n")                                              _d=_d.rstrip("\n")
        if not re.search(re.compile(r'[a-z]+',re.I),_d):                if not re.search(re.compile(r'[a-z]+',re.I),_d):
            continue                                                        continue 

        if re.search(r'^#',_d):                                         if re.search(r'^#',_d):
            continue                                                        continue 

        _d = re.sub(r'^\s+',r'',_d,count=1)                             _d = re.sub(r'^\s+',r'',_d,count=1)
        _d = re.sub(r'(\s+)$',r'',_d,count=1)                           _d = re.sub(r'(\s+)$',r'',_d,count=1)
        _d = re.sub(r'\s+',r' ',_d,count=1)                             _d = re.sub(r'\s+',r' ',_d,count=1)
        tmp = perllib.Array(perllib.split(r' ',_str(_d)))               tmp = perllib.Array(perllib.split(r' ',_str(_d)))

**Comment by snoopyjc** [comment]
-p is the default. 
-P turns off the use of perllib. 

-joe

**Comment by pateshix** [comment]
Yes –  I understand -p/default.

Q1: So does the latest v0.964 pythonizer convert each perllib/perl5lib call on the fly as multiple nested perl script?  Or do I need to install / import PyPl?

Some examples of perllib calls in v0.964 pythonizer Python output file:

import os,builtins,re,perllib,sys
from perllib import Die
perllib.init_package('main')
    if not ((INF:=perllib.open_(f"{sys.argv[1:][0]}", 'r'))):
    while (_d:=perllib.readline(INF)):
        tmp = perllib.Array(perllib.split(r' ',_str(_d)))
            TEMP = perllib.Array(tmp[1:1+(len(tmp)-1)])
                perllib.perl_print(f"check sweep setting: {multi_sweep}, exiting \n",end="")
    perllib.close(INF)
    if not ((INF:=perllib.open_(TC_DEF, 'r'))):
    tc = perllib.Array()
    while (_d:=perllib.readline(INF)):
        tc_def = perllib.Hash()
        tmp = perllib.Array(perllib.split(r',',_str(_d)))
                    tmp1 = perllib.Array(perllib.split(r'__',_str(tmp[itmp])))  ## NESTed perllib calls
                   tmp1 = perllib.Array(perllib.split(r'__',_str(tmp[itmp])))
                    tmp1 = perllib.Array(perllib.split(r'__',_str(tmp[itmp])))
    perllib.close(INF)
    return perllib.close(INF)
    if not ((INF:=perllib.open_(capoutfile, 'r'))):
    while (_d:=perllib.readline(INF)):
        tmp = perllib.Array(perllib.split(r' ',_str(_d)))
    perllib.close(INF)
    return perllib.close(INF)
    if not ((OUTFILE:=perllib.open_(OutputFile, 'w'))):
        raise Die(f"Cann't write to {OutputFile}: {perllib.OS_ERROR}\n")

**Comment by snoopyjc** [comment]
You can either set `PYTHONPATH=Directory Containing Pythonizer.pm` or run

    pip install perllib

**Comment by snoopyjc** [comment]
FYI @pateshix  I opened up the Issues and Discussions tabs on my version: https://github.com/snoopyjc/pythonizer/issues

**Comment by snoopyjc** [comment]
With -p (default) you either need to

pip install perllib

-or-

export PYTHONPATH=Path to where you installed pythonizer/pythonizer

The version of perllib should match the pythonizer version you are using. 

-joe
