### ISSUE TITLE
Possible typos in 2 files

### ISSUE THREAD

**Issue by dim6003** [softpano/pythonizer#2]
Hello there,
Great project!

pythonizer (why doesn't it have the .pl extension by the way?) at line 111 , a '%' character missing in front of ENV : `$HOME=%ENV{'HOME'}`
PerlScan.pm at line 326 : substr instead of subscr
Running it on ubuntu 20.04.1 (Perl 5.26) it fails on the code I try to convert, seems to enter a dead loop (if using it wth option -d5, I get unending series of : 
`Generated parcial line get_config([re.split(separ,))([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)
Generated parcial line get_config([re.split(separ,))([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([re.split(separ,)([
`
while converting line 234 from perl source. Seems to always hang at that line number, whatever I do in my perl source...

Hope this helps!

Edit: since I wrote the above, I noticed pre_pythonizer has issues with the following constructs, so I rewrote to avoid them, but still the same pb with my code (without any -d option, complains after a while that it encountered a deep recursion at pythonizer line 1483.
`comment after the opening { of an if,else,elsif etc
single line sub, eg sub my_function {return substr($0,1,1);}
single line if, elsif, else, eg if (<condition>) {print `Something";

Also noticed the following message in pre_pythonizer output : pre_-366E: Checking reformatted source code via perl -cw produced some errors (RC=65280). Please correct them before proceeding, 
although my original code has no errors. Seems due to moving all initial variables declaration into a main sub at the end of the file.

Edit2:
Also noticed that it doesn't like the `Block if(EXPR)` single line construct. Rewrote them, but still hanging.
comments after line ending semi-colon get lost.
doesn't like function calls without parenthesis eg foo= substr bar,0,2;

Edit3:
ok, I think I got to the code that puzzles pythonizer, it is a call to the perl standard "split" function, which expects as a first parameter a regex /abc/ (or in my case /$variable/). This case seems not taken care of in pythonizer, in function "expression". it's one of the rare cases when the regex /abc/ is not preceeded by any '~' character. Not ready to suggest a correction though!

**Comment by softpano** [comment]
Looks like you are using old version. Are you talking about version 0.8 ?  

If not, please try the latest version. I do not support any earlier versions and any ticket without information required according to the user guide (see  section on tickets in **user_guide.shtml** for details) will be ignored.  

NOTE: The newest version of **pre_pythonizer.pl** by default does not create main function (you need to use option -m to get this functionality)

If the pythonizer goes into infinite recursion, you can comment out the line or two and it will continue, while opening ticket on this  specific set of lines (the current line plus 10 before and 10 after) 

> while converting line 234 from perl source.

What is the context of this line? Can you please provide it with  10 "before" and  10 "after" lines. 

Can you please provide an example of Block if(EXPR) that pythonizer does not accept. It should accept all of them, even perverted like 
$i=5,$j=10 if ($last>0);

It just will be translated incorrectly. 

To increase changes of success you can also split your code into several chunks (for example main program and subs) and try to convert them chunk by chunk and  then add global declaration for the necessary variables manually.  

Please note that  option -d 5 will not work  without -d option in Perl interpreter and designed only for finding serious internal errors via debugger.  You should try -d 3 instead which will provide the trace.

**Comment by dim6003** [comment]
Hello, 


First tests where made with you commit dated september-19, last ones with the one dated october-2, so yes, I'm talking about version 0.8. 
Forget about the comment about line 234, it was based on what I got in the output .py file, which was missing part because of the caching proccess on file writes. 
While testing with -d 3, I got to the line which triggers this infinite loop, that is a call to the split function. 
Here's extract of the code, the offending line in bold: 


#rem analyse les parametres de config lus 
#rem -> utilisation de doubles quotes pour la transmission entre boucle FOR et call :get_config rendue nécessaire par une mauvaise gestion du séparateur ',' présent dans certains paramètres 

#For /F "tokens=1,2,3,4 delims=%separ%" %%s in (c:\report\lit_config_%procedure%_%variante%.cfg) do (call :get_config "%%s" "%%t" "%%u" "%%v") 
open(SORTIE,'>',$sortie) or die("open($sortie): $!"); 
open(SORTIE_VAR,'>',$sortie_var) or die("open($sortie_var): $!"); 
open(SQL_RSLT,'<',$sql_rslt) or die("open(\"$disque\\temp\\lit_config_$nom_script.cfg\"): $!"); 
while (<SQL_RSLT>) 
{ 
chomp; 
get_config(split /$separ/ ,$_); 
} 



close(SQL_RSLT) or die("close: $!"); 

if ($SQL_options ne '') 
{ 
config("SQL_options",$SQL_options) 
} 
if ($liste_SQL_var ne '') 
{ 
config("liste_SQL_var",$liste_SQL_var) 
} 
if ($liste_etendue_SQL_var ne '') 
{ 
config("liste_etendue_SQL_var",$liste_etendue_SQL_var) 
} 



adding the optionnal,$0 to the split function does not change anything, anyways it comes after the chunk that causes the issue from what I've seen tracing the code, chunk that I put in blue 



As my code does not contain anything private or confidential, I can send it to you, the original one that runs multipe times every day, and the one I modified to try go thru the pythonizer. Doing so you'll clearly see the changes I made regarding the "BLOCK if(expr)", and the issues when you have "if(expr) { # comment" , as welle as all the end-of-lin comments that are lost "expr; # comment". 



I do not consider myself an expert in perl coding, so you may find my coding is not perfect, but it does what I want, and that suits me! ;-) 


thanks 
Didier. 
----- Mail original -----

De: "softpano" <notifications@github.com> 
À: "softpano/pythonizer" <pythonizer@noreply.github.com> 
Cc: "dim6003" <dm.martin@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Lundi 5 Octobre 2020 07:58:11 
Objet: Re: [softpano/pythonizer] Possible typos in 2 files (#2) 



Looks like you are using old version. Are you talking about version 0.8 ? 
If not, please try the latest version. I do not support any earlier versions and any ticket without information required according to the user guide (see section on tickets in user_guide.shtml for details) will be ignored. 
NOTE: The newest version of pre_pythonizer.pl by default does not create main function (you need to use option -m to get this functionality) 
If the pythonizer goes into infinite recursion, you can comment out the line or two and it will continue, while opening ticket on this specific set of lines (the current line plus 10 before and 10 after) 


while converting line 234 from perl source. 


What is the context of this line? Can you please provide it with 10 "before" and 10 "after" lines. 
Can you please provide an example of Block if(EXPR) that pythonizer does not accept. It should accept all of them, even perverted like 
$i=5,$j=10 if ($last>0); 
It just will be translated incorrectly. 
To increase changes of success you can also split your code into several chunks (for example main program and subs) and try to convert them chunk by chunk and then add global declaration for the necessary variables manually. 
Please note that option -d 5 will not work without -d option in Perl interpreter and designed only for finding serious internal errors via debugger. You should try -d 3 instead which will provide the trace.

**Comment by softpano** [comment]
This is about recent Perl games with round parenthesis. They are attempt to catch Python and in some cases this  is pure evil.

This is syntactically ambiguous statement which should be flagged in Pre-pythonizer because  

get_config(split /$separ/ ,$_);

you can interpret it as a call with two arguments:
split /$separ/  and $_

So in this case round brackets are mandatory and that's might fix an error 

get_config(split(/$separ/ ,$_));

**Comment by dim6003** [comment]
maybe, but I think there's certainly some precedence rule somewhere. But before adding the optional ",$_" parameter to to call to split, the line was simply 

get_config(split /$separ/ ); 
and there is no such evil iN it, still it failed. 


Anyway, I changed it: get_config(split (/$separ/,$_)); 
and ran pythonizer again, and it still enters an infinite loop, after saying 

Line 597. $TokenStr: =|i(f/s/,s)|= @ValPy: get_config ( re.split / separ / , default_var ) 


But after changing it again to get_config(split (/$separ/ )); 
It finally did it through, with some complaints : 
ATTENTION! 
The following lines were probably translated incorrectly: 

[107]: END 
[120]: print LOG shift." : ".shift 
[129]: print SORTIE shift."\t".shift; # enregistre en "tab separated" 
[441]: undef $log 
[445]: undef $pid 
[453]: undef $variante ; 
[454]: undef $variante_OR_NULL; 
[455]: undef $variante_IS_NULL; 
[464]: undef $variante_OR_NULL; 
[465]: undef $variante ; 
[474]: undef $variante_IS_NULL; 
[483]: undef $variante_OR_NULL; 
[484]: undef $variante_IS_NULL; 
[526]: unlink $sortie_var;} 
[527]: unlink $sortie;} 
[543]: print REQ_SQL " And (variante=\'$variante\')" if ((defined $variante) and (!defined $variante_OR_NULL)); 
ERROR STATISTICS: W: 1 S: 6 


[Perlscan.pm-640S]: The value of cut (3) exceeded the length (1) of the string: " 

[Perlscan.pm-640S]: The value of cut (11) exceeded the length (9) of the string: ',qw/$/); 

LINE 98 [Perlscan.pm-640S]: The value of cut (3) exceeded the length (1) of the string: " 

LINE 120 [pythonizer-1319S]: Function shift should use brackets for arguments. '(' is not found after functionname 

LINE 129 [pythonizer-1319S]: Function shift should use brackets for arguments. '(' is not found after functionname 

LINE 413 [Perlscan.pm-640S]: The value of cut (11) exceeded the length (9) of the string: ',qw/$/); 




[Softpano.pm-322W]: Debug flag is set to 3 



*** PLEASE CHECK 6 SERIOUS MESSAGES ABOVE 
$s[/] $tno[4] $source[^source]$s[/] $tno[4] $source[^source]$s[/] $tno[4] $source[^source] 



----- Mail original -----

De: "softpano" <notifications@github.com> 
À: "softpano/pythonizer" <pythonizer@noreply.github.com> 
Cc: "dim6003" <dm.martin@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Lundi 5 Octobre 2020 21:10:05 
Objet: Re: [softpano/pythonizer] Possible typos in 2 files (#2) 



This is about recent Perl games with round parenthesis. They are attempt to catch Python and in some cases this is pure evil. 
This is syntactically ambiguous statement which should be flagged in Pre-pythonizer because 
get_config(split /$separ/ ,$_); 
you can interpret it as a call with two arguments: 
split /$separ/ and $_ 
So in this case round brackets are mandatory and that's might fix an error 
get_config(split(/$separ/ ,$_));

**Comment by softpano** [comment]
I have time today so I will correct some of those.

**Comment by dim6003** [comment]
By the way, you asked for an example of BLOCK if(expr) , there's one in the errors below, highlighted in yellow. 



The following lines were probably translated incorrectly: 

[107]: END 
[120]: print LOG shift." : ".shift 
[129]: print SORTIE shift."\t".shift; # enregistre en "tab separated" 
[441]: undef $log 
[445]: undef $pid 
[453]: undef $variante ; 
[454]: undef $variante_OR_NULL; 
[455]: undef $variante_IS_NULL; 
[464]: undef $variante_OR_NULL; 
[465]: undef $variante ; 
[474]: undef $variante_IS_NULL; 
[483]: undef $variante_OR_NULL; 
[484]: undef $variante_IS_NULL; 
[526]: unlink $sortie_var;} 
[527]: unlink $sortie;} 
[543]: print REQ_SQL " And (variante=\'$variante\')" if ((defined $variante) and (!defined $variante_OR_NULL)); 
ERROR STATISTICS: W: 1 S: 6 

Didier. 


----- Mail original -----

De: "softpano" <notifications@github.com> 
À: "softpano/pythonizer" <pythonizer@noreply.github.com> 
Cc: "dim6003" <dm.martin@free.fr>, "Author" <author@noreply.github.com> 
Envoyé: Lundi 5 Octobre 2020 22:30:54 
Objet: Re: [softpano/pythonizer] Possible typos in 2 files (#2) 



I have time today so I will correct some of those.

**Comment by softpano** [comment]
Got your email.

**Comment by softpano** [comment]
Analyzing the situation I found out that 

`get_config(split /$separ/ ,$_);`

is interpreted by Perl as 

`get_config(split( /$separ/) ,$_);`

not as 

`get_config(split( /$separ/ ,$_));`

**Comment by softpano** [comment]
Analyzing the situation I found out that

get_config(split /$separ/ ,$_);

is interpreted by Perl as

get_config(split( /$separ/ ,$_)); # two argument for split, resulting list for  get_config

not as

get_config(split( /$separ/ ),$_); $ one argument for split and the second argument to get_config

Function Undef will be parsed correctly inversion 8.2 when I post it. But here again "bracket-less" invocations are OK in statements only; not in expressions.  In expressions they always will be a problem for pythonizer.  
You  can attach file to your comment, if you wish that I work on this case more.

**Comment by softpano** [comment]
I posted version 8,2 that corrects some errors.

**Comment by snoopyjc** [comment]
Hi @dim6003 

Please check out my new pythonizer here: https://github.com/snoopyjc/pythonizer

It's got all the reported bugs in the SoftPano version fixed!

--joe
