### ISSUE TITLE
had to reboot my linux box after running pythonizer

### ISSUE THREAD

**Issue by tedx** [softpano/pythonizer#3]
It's hard to know why/how but the only recovery from a run of pythonizer was to reboot my box which became unresponsive. Also I ran pre_pythonizer.pl on the perl script I'm trying to convert but the perl it output will not run is this behavior to be expected?

**Comment by softpano** [comment]
> It's hard to know why/how but the only recovery from a run of pythonizer was to reboot my box which became unresponsive

Pythonizer is a text processing program. Generally it does not affect  operating system state unless you have problems with the filesystem on which the source is located.

**Comment by softpano** [comment]
> Also I ran pre_pythonizer.pl on the perl script I'm trying to convert but the perl it output will not run is this behavior to be expected?

Pre pythonizer should not introduce new errors in the script.  But you can try to convert the script without running it first. It just improves the chances of success. 

If you want me to look at the problem please provide listings.

**Comment by softpano** [comment]
No response from the affected user
