### ISSUE TITLE
License for repo?

### ISSUE THREAD

**Issue by firasm** [softpano/pythonizer#5]
Hello,

I’m a faculty member at the University in British Columbia and my group just got a small grant to convert some old homework and test problems from Perl to python. 

We are interested in testing your package/work for our purposes but one of the requirements of the output we produce is that it can’t have any dependencies that are closed source. 

Would you be interested in attaching a license to this repo? I’m happy to submit a PR for this if you let me know which license you’d prefer. 

https://choosealicense.com

Thanks in advance!

**Comment by softpano** [comment]
Hi Firas,

    >I’m a faculty member at the University in British Columbia and my group just got a small grant to convert some old homework and test problems from Perl to python.

Looks like an interesting application to me.  This software should be able to handle such simple scripts.

  > Would you be interested in attaching a license to this repo? I’m happy to submit a PR for this if you let me know which license you’d prefer.

Sorry about that. Like the majority of Perl open source, the software was licensed under Perl Artistic License.

    ## Copyright Nikolai Bezroukov, 2019-2020.
    ## Licensed under Perl Artistic license

I uploaded the license to GitHub.

See The "Artistic License" - dev.perl.org
Artistic License - Wikipedia
Category:Software using the Artistic license - Wikipedia

**Comment by firasm** [comment]
Thank you !
